name: Build and Push Unraid Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'Dockerfile.unraid.new'
      - 'deploy/nginx/**'
      - '.github/workflows/docker-unraid.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: spicyricecakes/hoof-hearted

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=raw,value=unraid-v2
          type=raw,value=latest

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.unraid.new
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Update Unraid template with new image
      run: |
        sed -i 's|<Repository>.*</Repository>|<Repository>${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:unraid-v2</Repository>|' deploy/unraid/hoof-hearted-template.xml
        sed -i 's|<Registry>.*</Registry>|<Registry>https://github.com/SpicyRiceCakes/hoof-hearted/pkgs/container/hoof-hearted</Registry>|' deploy/unraid/hoof-hearted-template.xml

    - name: Commit updated template
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add deploy/unraid/hoof-hearted-template.xml
        git diff --staged --quiet || git commit -m "🐎 Update Unraid template with new container registry

        🚀 Auto-updated by GitHub Actions
        📦 New image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:unraid-v2
        🌶️ Built with SpicyRiceCakes methodology"
        git push